#
###################################
# Site wide configuration
####################################
#
title: honestbee
email:
description: This blog features articles written by our engineering team.
url: # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Singapore
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:categories/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: honestbee
  avatar: primary-logo.png
  job:
  bio: "On Demand Platform. Making lives easy"
  email: hireme+techblog@honestbee.com
  disqus-shortname:
  twitter: honestbeesg
  facebook: honestbee
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: honestbee
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin:
    company: true
    username: honestbee
  skype: #username
  xing: #username
  instagram: honestbeesg
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  hiring:
    status: true
    link: http://careers.honestbee.com/departments/engineering/

#
###################################
# Authors
####################################
#
authors:
  Charles Martinot:
    linkedin: charlesmartinot
    twitter:
  Mingsheng Gan:
    linkedin: mingsheng-gan-92b23028
    twitter:
  Taher Dhilawala:
    linkedin: tahernd
    twitter:
  Vincent De Smet:
    linkedin: vincentds
    twitter: vincentdesmet
  Tuan Nguyen:
    linkedin: tuannvm
    twitter: tuannvm
